### PR TITLE
Changed Zend consts to Laminas

### PR DESCRIPTION
**Pull request by nikita-sedletskiy-ambientia**
Fixes issue with dependency to Zend framework after updating magento 2.4.6. Changed Zend to Laminas

### CODE REVIEW

**Comment by juhanihaapala** [comment]
Request is not using Laminas, but Guzzle so I it is not causing the error.

**Comment by nikita-sedletskiy** [comment]
I mean Laminas (that suggested to use from 2.4.6-p3) is working a bit different way than implementation that is done now, so  i guess you probably have to change from Zend and Guzzle to it

**Comment by juhanihaapala** [comment]
Finally got to test the payment, but I don't get any error with it. I'll merge this pr and do a release, if you find out how reproduce the 403 forbidden error, please open new issue for it.

**Review by juhanihaapala — APPROVED** [review]

**Comment by nikita-sedletskiy** [comment]
We getting 403 with this patch after updating to 2.4.6-p3, before that (on p2) it was working, in p3 Zend was removed, i guess it causes issue. Make sure that there is correct magento version without zend framework while reproducing issue

**Comment by juhanihaapala** [comment]
@nikita-sedletskiy we got other complaints also about the the 403 and I finally found why it happened. In this pr you accidentally changed the transferclient method to be by default GET which then caused the 403 errors. 

It is now fixed in latest release 1.0.12.

**Pull request merged**
